version: 0.2

env: 
  parameter-store: 
    DOCKERHUB_USER: 'AW_DOCKERHUB_USERNAME'
    DOCKERHUB_PW: 'AW_DOCKERHUB_PW'

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- $(aws ecr get-login --region ap-southeast-2 --no-include-email)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 245866473499.dkr.ecr.ap-southeast-2.amazonaws.com
      - IMAGE_REPO_NAME=uat-cheetah
      - REPOSITORY_URI=245866473499.dkr.ecr.ap-southeast-2.amazonaws.com/uat-cheetah 
      #- IMAGE_REPO_NAME=async-working
      #- REPOSITORY_URI=245866473499.dkr.ecr.ap-southeast-2.amazonaws.com/async-working
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo ${IMAGE_TAG}
      - echo ${COMMIT_HASH}
      - echo ${AWS_DEFAULT_REGION}
      - whoami
      - pwd
      - ls -al
      - uname -a
      
  build:
    commands:
      - echo Build started on `date`
      - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_USER --password-stdin
      - whoami
      - pwd
      - ls -al
      - docker images
      # - docker-compose up -d
      - echo Building the Docker image...
      - docker images
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker ps
      - docker images
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker images
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - ls -al
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - pwd
      - ls -al
      - printf '[{"name":"uat-cheetah-0608","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - aws s3 cp imagedefinitions.json s3://codepipeline-ap-southeast-2-cheetah-uat-aritifacts/artifacts/
artifacts:
  files: imagedefinitions.json
