server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=uatawcheetah
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: uatawcheetah
  jpa:
    properties:
      hibernate:
        default_schema: uatawcheetah
        jdbc:
          time_zone: UTC
    show-sql: true

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.asyncworking: debug

#production env
url: https://uat.asyncworking.com

#local env
#url: http://localhost:3000


jwt:
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
  secretKey: 7756adfasdfenci,,@@33$$*()sdfsdkjhsnklp999002qejf\\//asdf



cloud:
  aws:
    region:
      static: ap-southeast-2
      auto: false
    sqs:
      incoming-queue:
        name: AWRECEIVEQ
        url: http://localhost:4566/000000000000/AWRECEIVEQ
      outgoing-queue:
        name: AWVerificationEmailBasicPP
        url: http://localhost:4566/000000000000/AWVerificationEmailBasicPP
      stack:
        auto: false
      credentials:
        accesskey: test
        secretkey: test
      endpoint: http://localhost:4566/
    S3:
      templateS3Bucket: aw-email-template-jh
      templateS3Key: verification_email_template.txt
    endpoint: http://localhost:4566

#cloud:
#  aws:
#    region:
#      static: ap-southeast-2
#      auto: false
#    sqs:
#      incoming-queue:
#        name: Outcome
#        url: https://sqs.ap-southeast-2.amazonaws.com/780378238023/Outcome
#      outgoing-queue:
#        name: aw_email_service
#        url: https://sqs.ap-southeast-2.amazonaws.com/780378238023/aw_email_service
#    stack:
#      auto: false
#    credentials:
#      access-key: AKIA3LMRK5RDTNBHPGIS
#      secret-key: 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
#    S3:
#      templateS3Bucket: aw-email-template-jh
#      templateS3Key: verification_email_template.txt
#
#    endpoint: https://sqs.ap-southeast-2.amazonaws.com

sqs:
  enable: true