server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=awcheetah
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: awcheetah
  jpa:
    properties:
      hibernate:
        default_schema: awcheetah
        jdbc:
          time_zone: UTC
    show-sql: true

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.asyncworking: debug

#production env
url: https://www.asyncworking.com

#local env
#url: http://localhost:3000

jwt:
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure

  secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecures

#cloud:
#  aws:
#    region:
#      static: ap-southeast-2
#      auto: false
#    sqs:
#      incomingqueue:
#        name: AW_RECEIVE_Q
#        url: http://localhost:4566/000000000000/AW_RECEIVE_Q
#      outgoingqueue:
#        name: AWVerificationEmailBasicPP
#        url: http://localhost:4566/000000000000/AWVerificationEmailBasicPP
#    stack:
#      auto: false
#    credentials:
#      accesskey: test
#      secretkey: test
#    S3:
#      templateS3Bucket: aw-email-template
#      templateS3Key: verification_email_template.txt
#    endpoint: http://localhost:4566
cloud:
  aws:
    region:
      static: ap-southeast-2
      auto: false
    sqs:
      incoming-queue:
        name: Outcome
        url: https://sqs.ap-southeast-2.amazonaws.com/780378238023/Outcome
      outgoing-queue:
        name: aw_email_service
        url: https://sqs.ap-southeast-2.amazonaws.com/780378238023/aw_email_service
    stack:
      auto: false
    credentials:
      access-key: AKIA3LMRK5RDTNBHPGIS
      secret-key: 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
    S3:
      templateS3Bucket: aw-email-template-jh
      templateS3Key: verification_email_template.txt

    endpoint: https://sqs.ap-southeast-2.amazonaws.com

sqs:
  enable: true