server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=awcheetah
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: awcheetah
  jpa:
    properties:
      hibernate:
        default_schema: awcheetah
        jdbc:
          time_zone: UTC
    show-sql: true

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.asyncworking: debug

url: https://www.asyncworking.com


jwt:
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure

cloud:
  aws:
    region:
      static: ap-southeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAYJZSMLQCAMSE23MO
      secret-key: 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
    end-point:
      uri: https://sqs.ap-southeast-2.amazonaws.com/570799447044/DemoQueue