server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=uatawcheetah
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: uatawcheetah
  jpa:
    properties:
      hibernate:
        default_schema: uatawcheetah
        jdbc:
          time_zone: UTC
    show-sql: true


# esctosqs:
#   ECS_SQS_USER_KEY: AW_ECS_SQS_USER_KEY
#   ECS_SQS_USER_ACCESS: AW_ECS_SQS_USER_ACCESS

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.asyncworking: debug

#production env
url: https://uat.asyncworking.com

#local env
#url: http://localhost:3000


jwt:
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
  secretKey: 7756adfasdfenci,,@@33$$*()sdfsdkjhsnklp999002qejf\\//asdf



cloud:
  aws:
    region:
      static: ap-southeast-2
      auto: false
    sqs:
      incoming-queue:
        name: AW_RECEIVE_Q
        url: https://sqs.ap-southeast-2.amazonaws.com/245866473499/AW_RECEIVE_Q
      outgoing-queue:
        name: AWVerificationEmailBasicPP
        url: https://sqs.ap-southeast-2.amazonaws.com/245866473499/AWVerificationEmailBasicPP
    stack:
      auto: false
    credentials:
      access-key: ECS_SQS_USER_KEY
      secret-key: ECS_SQS_USER_ACCESS

# env:
#   parameter-store:
#     ECS_SQS_USER_KEY: "AW_ECS_SQS_USER_KEY"
#     ECS_SQS_USER_ACCESS: "AW_ECS_SQS_USER_ACCESS"