server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=awcheetah
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: awcheetah
  jpa:
    properties:
      hibernate:
        default_schema: awcheetah
        jdbc:
          time_zone: UTC
    show-sql: true

swagger_env: dev

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    com.asyncworking: debug

#production env
#url: https://www.asyncworking.com

#local env
url: http://localhost:3000

jwt:
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure

  secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecures

cloud:
  aws:
    region:
      static: ap-southeast-2
      auto: false
    sqs:
      incomingqueue:
        name: AW_RECEIVE_Q
        url: http://localhost:4566/000000000000/AW_RECEIVE_Q
      outgoingqueue:
        name: AWVerificationEmailBasicPP
        url: http://localhost:4566/000000000000/AWVerificationEmailBasicPP
    stack:
      auto: false
    credentials:
      accesskey: test
      secretkey: test
    S3:
      templateS3Bucket: aw-email-template
      templateS3Key: verification_email_template_updated.html
      templateResetPasswordS3Key: reset_password_email_template.txt
      templateCompanyInvitationS3Key: company_invitation_email_template.html
    endpoint: http://localhost:4566

sqs:
  enable: true
